syntax = "proto3";

package user;

option go_package = "./user";

message Empty {}

message RegisterRequest {
  string username = 1;
  string password = 2;
  string nickname = 3;
  string email = 4;
  string email_code = 5;
  string wallet_addr = 6;
  string referral_code = 7;
  string captcha_id = 8;
  string captcha_code = 9;
}

message RegisterResponse {
  int64 id = 1;
  string username = 2;
  string nickname = 3;
  string email = 4;
  string wallet_addr = 5;
  string user_referral_code = 6;
  string referral_code = 7;
}

message LoginRequest {
  string username = 1;
  string password = 2;
  string captcha_id = 3;
  string captcha_code = 4;
}

message LoginResponse {
  string token = 1;
  int64 user_id = 2;
  string username = 3;
  string nickname = 4;
  string email = 5;
  string wallet_addr = 6;
  string user_referral_code = 7;
  string referral_code = 8;
}

message GetUserInfoResponse {
  int64 id = 1;
  string username = 2;
  string nickname = 3;
  string email = 4;
  string wallet_addr = 5;
  string user_referral_code = 6;
  string referral_code = 7;
}

message UpdateUserInfoReqest {
  string nickname = 1;
  string wallet_addr = 2;
}

message ChangePassWdRequest {
  string email = 1;
  string code = 2;
  string new = 3;
}

message CaptchaResponse {
  string captcha_id = 1;
  string img_base64 = 2;
}

message SendEmailRequest {
  string email = 1;
}

message SendEmailResponse {
  bool success = 1;
}

message LoginLogResponse {
  repeated LoginLog login_logs = 1;
}

message LoginLog {
  uint64 user_id = 1;
  string status = 2;
  string ip_addr = 3;
  string location = 4;
  string browser = 5;
  string os = 6;
  string platform = 7;
  int64  login_time = 8;
  string remark = 9;
  string msg = 10;
}

message GetLoginLogRequest {
  uint64 page = 1;
}

message DeleteLoginLogRequest {
  uint64 id = 1;
}

service User {
  rpc Register (RegisterRequest) returns (RegisterResponse);
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc GetLoginLog (GetLoginLogRequest) returns (LoginLogResponse);
  rpc DeleteLoginLog (DeleteLoginLogRequest) returns (Empty);
  rpc GetUserInfo (Empty) returns (GetUserInfoResponse);
  rpc UpdateUserInfo (UpdateUserInfoReqest) returns (Empty);
  rpc ChangePassword (ChangePassWdRequest) returns (Empty);
  rpc GenerateCaptcha (Empty) returns (CaptchaResponse);
  rpc SendEmail (SendEmailRequest) returns (SendEmailResponse);
}