// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package user_client

import (
	"context"

	"github.com/xxx-newbee/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChangePassWdRequest    = user.ChangePassWdRequest
	ChangePassWdResponse   = user.ChangePassWdResponse
	GetUserInfoRequest     = user.GetUserInfoRequest
	GetUserInfoResponse    = user.GetUserInfoResponse
	LoginRequest           = user.LoginRequest
	LoginResponse          = user.LoginResponse
	RegisterRequest        = user.RegisterRequest
	RegisterResponse       = user.RegisterResponse
	UpdateUserInfoReqest   = user.UpdateUserInfoReqest
	UpdateUserInfoResponse = user.UpdateUserInfoResponse

	User interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReqest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error)
		ChangePassword(ctx context.Context, in *ChangePassWdRequest, opts ...grpc.CallOption) (*ChangePassWdResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUser) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReqest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultUser) ChangePassword(ctx context.Context, in *ChangePassWdRequest, opts ...grpc.CallOption) (*ChangePassWdResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}
