// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package user_client

import (
	"context"

	"github.com/xxx-newbee/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CaptchaResponse      = user.CaptchaResponse
	ChangePassWdRequest  = user.ChangePassWdRequest
	Empty                = user.Empty
	GetUserInfoResponse  = user.GetUserInfoResponse
	LoginRequest         = user.LoginRequest
	LoginResponse        = user.LoginResponse
	RegisterRequest      = user.RegisterRequest
	RegisterResponse     = user.RegisterResponse
	UpdateUserInfoReqest = user.UpdateUserInfoReqest

	User interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		GetUserInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReqest, opts ...grpc.CallOption) (*Empty, error)
		ChangePassword(ctx context.Context, in *ChangePassWdRequest, opts ...grpc.CallOption) (*Empty, error)
		GenerateCaptcha(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CaptchaResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) GetUserInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUser) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReqest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultUser) ChangePassword(ctx context.Context, in *ChangePassWdRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

func (m *defaultUser) GenerateCaptcha(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CaptchaResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GenerateCaptcha(ctx, in, opts...)
}
